import _ from 'lodash';
import {Board} from '../js/board.js';

describe('Board', function() {
  it('is initialized with a dimension', function () {
    var b = new Board(5, 6);
    expect(b.height).toEqual(5);
    expect(b.width).toEqual(6);
    expect(b.grid.length).toEqual(5);
    expect(b.grid[0].length).toEqual(6);
  });

  it('mark marks the position in the grid with a klass', function () {
    var b = new Board(5, 6);
    b.mark([1, 1], 'x');
    expect(b.at([0, 0])).toEqual(null);
    expect(b.at([1, 1])).toEqual('x');
  });

  it('place marks all cells generated by the tile', function () {
    var b = new Board(5, 6);
    var fakeTile = {
      cells: () => [[1, 1], [1, 2]],
      klass: 'x'
    };
    b.place(fakeTile);
    expect(b.empty([0, 0])).toBe(true);
    expect(b.at([1, 1])).toEqual('x');
    expect(b.at([1, 2])).toEqual('x');
  });

  it('empty is true if no tile type class is on the grid', function () {
    var b = new Board(5, 6);
    expect(b.empty([0, 0])).toEqual(true);
  });
});
